#!/bin/bash

SCRIPT_FOLDER="$HOME/scripts"
SCRIPT_FILE="$SCRIPT_FOLDER/$1"

if [[ -f $SCRIPT_FILE ]]; then
	sudo vim $SCRIPT_FILE
else
	echo '#!/bin/bash' > $SCRIPT_FILE
	chmod +x $SCRIPT_FILE
	sudo vim $SCRIPT_FILE
fi
